package com.beniregev.springcucumberexampleapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * SpringBootApplication generated by Spring Boot initializer
 * @author Binyamin Regev
 * @since 1.8
 */
@SpringBootApplication
public class SpringCucumberExampleAppApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringCucumberExampleAppApplication.class, args);
    }

}
